### ISSUE TITLE
did you code this

### ISSUE THREAD

**Issue by Ioluse** [SadlySpin/Skyblock-8Kb-Rat#2]
did you code this

**Comment by Ioluse** [comment]
im just askin bro

**Comment by Ioluse** [comment]
i saw it while searching on github

**Comment by SadlySpin** [comment]
Yh ok if u have any questions contact me on discord Spin#1010

**Comment by Ioluse** [comment]
> Yh ok if u have any questions contact me on discord Spin#1010

You did make this? or did you get it somewhere, im just tryna not get ratted

**Comment by SadlySpin** [comment]
Bro it’s a fucking rat, if u run it nothing is going to happen because I
termed all the web hooks u monkey

**Comment by Ioluse** [comment]
learn how to code your own rat 🤣 stop skidding for once lil bro

**Comment by SadlySpin** [comment]
Who tf is u? Actual pooron

**Comment by Ioluse** [comment]
you think editing the discord hook name makes it your rat? 😁code ur own skid
